@echo off
chcp 65001
title LogTool Windows Setup Script

echo ========================================
echo    LogTool Windows 部署配置脚本
echo ========================================
echo.

REM 检查管理员权限
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo [错误] 请以管理员权限运行此脚本！
    pause
    exit /b 1
)

echo [1/6] 检查环境...
echo.

REM 检查 Node.js
node --version >nul 2>&1
if errorlevel 1 (
    echo [错误] 未找到 Node.js，请先安装 Node.js 16+
    pause
    exit /b 1
) else (
    echo [√] Node.js 已安装
    node --version
)

REM 检查 MySQL
mysql --version >nul 2>&1
if errorlevel 1 (
    echo [警告] 未找到 MySQL，请确保 MySQL 已安装并运行
) else (
    echo [√] MySQL 已安装
    mysql --version
)

REM 检查 Redis
if exist "infrastructure\Redis\redis-server.exe" (
    echo [√] Redis 已找到
) else (
    echo [警告] 未找到 Redis，请确保 Redis 已安装
)

echo.
echo [2/6] 配置防火墙规则...
echo.

REM 开放端口
netsh advfirewall firewall show rule name="LogTool HTTP" >nul 2>&1
if errorlevel 1 (
    netsh advfirewall firewall add rule name="LogTool HTTP" dir=in action=allow protocol=TCP localport=80
    echo [√] 已添加 HTTP 端口规则
) else (
    echo [√] HTTP 端口规则已存在
)

netsh advfirewall firewall show rule name="LogTool API" >nul 2>&1
if errorlevel 1 (
    netsh advfirewall firewall add rule name="LogTool API" dir=in action=allow protocol=TCP localport=3000
    echo [√] 已添加 API 端口规则
) else (
    echo [√] API 端口规则已存在
)

echo.
echo [3/6] 检查项目配置...
echo.

REM 检查后端 .env 文件
if not exist "backend\.env" (
    echo [警告] 未找到 backend\.env 文件
    echo 请参考 WINDOWS_DEPLOYMENT_GUIDE.md 创建 .env 文件
) else (
    echo [√] backend\.env 文件已存在
)

REM 检查前端构建
if not exist "frontend\dist\index.html" (
    echo [警告] 前端未构建，正在构建...
    cd frontend
    call npm install
    call npm run build
    cd ..
    if exist "frontend\dist\index.html" (
        echo [√] 前端构建完成
    ) else (
        echo [错误] 前端构建失败
        pause
        exit /b 1
    )
) else (
    echo [√] 前端已构建
)

echo.
echo [4/6] 配置 Nginx...
echo.

set /p NGINX_PATH="请输入 Nginx 安装路径 (例如: C:\nginx): "
if not exist "%NGINX_PATH%\nginx.exe" (
    echo [错误] 未找到 Nginx，请检查路径
    pause
    exit /b 1
)

set /p FRONTEND_PATH="请输入前端文件部署路径 (例如: C:\www\logtool): "
if not exist "%FRONTEND_PATH%" (
    echo 创建前端文件目录...
    mkdir "%FRONTEND_PATH%"
)

echo 复制前端文件...
xcopy /E /I /Y "frontend\dist\*" "%FRONTEND_PATH%\" >nul
echo [√] 前端文件已复制到 %FRONTEND_PATH%

echo.
echo 配置 Nginx...
set /p SERVER_NAME="请输入服务器名称 (IP 或域名，例如: 192.168.1.100 或 logtool.local): "

REM 创建 Nginx 配置文件
(
echo # LogTool Nginx Configuration for Windows
echo # Generated by setup-windows.bat
echo.
echo map $http_user_agent $is_mobile {
echo     default 0;
echo     ~*android^|webos^|iphone^|ipad^|ipod^|blackberry^|iemobile^|opera\smini^|mobile^|palm^|windows\sphone 1;
echo     ~*Mobile^|Mobile^|MOBILE 1;
echo }
echo.
echo server {
echo     listen 80;
echo     server_name %SERVER_NAME%;
echo     root %FRONTEND_PATH:/=\%;
echo     index index.html;
echo     access_log %NGINX_PATH:/=\%\logs\logtool-access.log;
echo     error_log %NGINX_PATH:/=\%\logs\logtool-error.log;
echo     charset utf-8;
echo.
echo     location ~* \.\(js^|css^|png^|jpg^|jpeg^|gif^|ico^|svg^|woff^|woff2^|ttf^|eot\)$ {
echo         expires 1y;
echo         add_header Cache-Control "public, immutable";
echo         access_log off;
echo         try_files $uri =404;
echo     }
echo.
echo     location /api {
echo         proxy_pass http://localhost:3000;
echo         proxy_http_version 1.1;
echo         proxy_set_header Upgrade $http_upgrade;
echo         proxy_set_header Connection 'upgrade';
echo         proxy_set_header Host $host;
echo         proxy_set_header X-Real-IP $remote_addr;
echo         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
echo         proxy_set_header X-Forwarded-Proto $scheme;
echo         proxy_connect_timeout 60s;
echo         proxy_send_timeout 60s;
echo         proxy_read_timeout 60s;
echo         proxy_buffering off;
echo     }
echo.
echo     location /health {
echo         proxy_pass http://localhost:3000/health;
echo         proxy_http_version 1.1;
echo         proxy_set_header Host $host;
echo         proxy_set_header X-Real-IP $remote_addr;
echo         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
echo         proxy_connect_timeout 5s;
echo         proxy_send_timeout 5s;
echo         proxy_read_timeout 5s;
echo         proxy_buffering off;
echo     }
echo.
echo     location /ws {
echo         proxy_pass http://localhost:3000;
echo         proxy_http_version 1.1;
echo         proxy_set_header Upgrade $http_upgrade;
echo         proxy_set_header Connection "Upgrade";
echo         proxy_set_header Host $host;
echo         proxy_set_header X-Real-IP $remote_addr;
echo         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
echo         proxy_set_header X-Forwarded-Proto $scheme;
echo         proxy_connect_timeout 7d;
echo         proxy_send_timeout 7d;
echo         proxy_read_timeout 7d;
echo     }
echo.
echo     location = /m {
echo         return 301 /m/;
echo     }
echo.
echo     location ^~ /m/ {
echo         try_files $uri $uri/ /index.html;
echo     }
echo.
echo     location = / {
echo         if ($is_mobile) {
echo             return 301 /m;
echo         }
echo         try_files $uri $uri/ /index.html;
echo     }
echo.
echo     location = /login {
echo         if ($is_mobile) {
echo             return 301 /m/login;
echo         }
echo         try_files $uri $uri/ /index.html;
echo     }
echo.
echo     location = /register {
echo         if ($is_mobile) {
echo             return 301 /m/login;
echo         }
echo         try_files $uri $uri/ /index.html;
echo     }
echo.
echo     location / {
echo         try_files $uri $uri/ /index.html;
echo     }
echo.
echo     client_max_body_size 500M;
echo     client_body_buffer_size 128k;
echo     client_body_timeout 60s;
echo     client_header_timeout 60s;
echo }
) > "%NGINX_PATH%\conf\logtool.conf"

echo [√] Nginx 配置文件已创建: %NGINX_PATH%\conf\logtool.conf
echo.
echo 请手动编辑 %NGINX_PATH%\conf\nginx.conf
echo 在 http 块中添加: include logtool.conf;
echo 或直接替换 server 块内容

echo.
echo [5/6] 安装 PM2...
echo.

npm list -g pm2 >nul 2>&1
if errorlevel 1 (
    echo 正在安装 PM2...
    npm install -g pm2
    echo [√] PM2 已安装
) else (
    echo [√] PM2 已安装
)

echo.
echo [6/6] 配置完成！
echo.
echo ========================================
echo    部署配置摘要
echo ========================================
echo.
echo 前端文件路径: %FRONTEND_PATH%
echo Nginx 路径: %NGINX_PATH%
echo 服务器名称: %SERVER_NAME%
echo.
echo 下一步操作:
echo 1. 检查并配置 backend\.env 文件
echo 2. 初始化数据库（如果未初始化）
echo 3. 启动 Redis: infrastructure\Redis\start-redis.bat
echo 4. 启动后端: pm2 start ecosystem.config.js
echo 5. 启动 Nginx: %NGINX_PATH%\nginx.exe
echo 6. 访问: http://%SERVER_NAME%
echo.
echo 详细说明请参考: WINDOWS_DEPLOYMENT_GUIDE.md
echo.
pause

